packages:
  - packages/*
  - '!playgrounds'
  - scripts
  - website
catalog:
  '@antfu/eslint-config': ^3.8.0
  '@antfu/ni': ^0.23.0
  '@commitlint/cli': ^19.5.0
  '@commitlint/config-conventional': ^19.5.0
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-replace': ^6.0.1
  '@testing-library/jest-dom': ^6.6.2
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.0.1
  '@pansy/copy-to-clipboard': ^1.0.8
  '@pansy/scrollbar-width': ^1.0.0
  '@types/nprogress': ^0.2.3
  '@types/supercluster': ^7.1.3
  '@types/node': ^22.5.4
  '@types/react': ^18.3.5
  '@types/react-dom': ^18.3.0
  '@vitest/ui': ^2.1.4
  '@vitest/coverage-v8': ^2.1.4
  '@zag-js/element-size': ^0.77.0
  bumpp: ^9.8.0
  chalk: ^5.3.0
  consola: ^3.2.3
  cross-spawn: ^7.0.3
  export-size: ^0.7.0
  eslint: ^9.13.0
  eslint-plugin-react: ^7.37.2
  eslint-plugin-react-hooks: ^5.0.0
  eslint-plugin-react-refresh: ^0.4.14
  es-toolkit: ^1.26.1
  fake-indexeddb: ^6.0.0
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  gray-matter: ^4.0.3
  husky: ^9.1.6
  jsdom: ^25.0.1
  lint-staged: ^15.2.10
  msw: ^2.6.0
  mqtt: ^4.3.8
  nprogress: ^0.2.0
  screenfull: ^6.0.2
  supercluster: ^8.0.1
  node-fetch: ^3.3.2
  ora: ^8.1.0
  plop: ^4.0.1
  prettier: ^3.3.3
  raf-stub: ^3.0.0
  react: ^18.3.1
  react-dom: ^18.3.1
  rimraf: ^6.0.1
  rollup: ^4.24.3
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  rollup-plugin-pure: ^0.2.1
  radash: ^12.1.0
  type-fest: ^4.26.1
  user-agent-data-types: ^0.4.2
  simple-git: ^3.27.0
  taze: ^0.18.0
  tsx: ^4.19.2
  typescript: ^5.6.3
  vite: ^5.4.10
  vitest: ^2.1.4
  yaml: ^2.6.0
