packages:
  - packages/*
  - '!playgrounds'
  - scripts
  - website
catalog:
  '@antfu/eslint-config': ^2.8.0
  '@antfu/ni': ^0.23.0
  '@commitlint/cli': ^19.4.1
  '@commitlint/config-conventional': ^19.4.1
  '@rollup/plugin-json': ^6.1.0
  '@rollup/plugin-replace': ^5.0.7
  '@testing-library/jest-dom': ^6.5.0
  '@testing-library/dom': ^10.4.0
  '@testing-library/react': ^16.0.1
  '@pansy/copy-to-clipboard': ^1.0.8
  '@pansy/scrollbar-width': ^1.0.0
  '@types/nprogress': ^0.2.3
  '@types/supercluster': ^7.1.3
  '@types/react': ^18.3.5
  '@types/react-dom': ^18.3.0
  '@vitest/ui': ^2.0.5
  '@vitest/coverage-v8': ^2.0.5
  '@zag-js/element-size': ^0.65.1
  bumpp: ^9.5.2
  chalk: ^5.3.0
  consola: ^3.2.3
  cross-spawn: ^7.0.3
  export-size: ^0.7.0
  eslint: ^8.57.0
  eslint-plugin-react: ^7.35.2
  eslint-plugin-react-hooks: ^4.6.2
  eslint-plugin-react-refresh: ^0.4.11
  fake-indexeddb: ^6.0.0
  fast-glob: ^3.3.2
  fs-extra: ^11.2.0
  gray-matter: ^4.0.3
  husky: ^9.1.5
  jsdom: ^25.0.0
  lint-staged: ^15.2.10
  msw: ^2.4.2
  mqtt: ^4.3.8
  nprogress: ^0.2.0
  screenfull: ^6.0.2
  supercluster: ^8.0.1
  node-fetch: ^3.3.2
  ora: ^8.1.0
  plop: ^4.0.1
  prettier: ^3.3.3
  raf-stub: ^3.0.0
  react: ^18.3.1
  react-dom: ^18.3.1
  rimraf: ^6.0.1
  rollup: ^4.21.2
  rollup-plugin-dts: ^6.1.1
  rollup-plugin-esbuild: ^6.1.1
  rollup-plugin-pure: ^0.2.1
  radash: ^12.1.0
  type-fest: ^4.26.0
  user-agent-data-types: ^0.4.2
  simple-git: ^3.26.0
  taze: ^0.16.7
  tsx: ^4.19.0
  typescript: ^5.5.4
  vite: ^5.4.3
  vitest: ^2.0.5
