name: 🛡 Lint + 🧪 Test

env:
  HUSKY: 0
  NODE_OPTIONS: --max-old-space-size=6144

on:
  push:
    branches:
      - main
      - next

  pull_request:
    branches:
      - main
      - next

  merge_group: {}

jobs:
  test:
    name: 🧪 Test
    timeout-minutes: 10
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node: [18.x, 20.x]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Set node version to ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - name: Install
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Typecheck
        run: pnpm typecheck

      - name: Test
        run: pnpm test

      - if: matrix.node == '18.x'
        name: Playground Smoke Test
        run: cd playgrounds && bash ./build.sh
